### ISSUE TITLE
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames:

### ISSUE THREAD

**Issue by siddiquiaffan** [Takeout-bysourfruit/takeout.js#2]
Got error while calling api through javascript sdk

Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: api.takeout.io. is not in the cert's altnames: DNS:undeveloped.com, DNS:undeveloped.es, DNS:undeveloped.cn, DNS:undeveloped.uk, DNS:undeveloped.eu, DNS:undeveloped.us, DNS:undeveloped.nl, DNS:undeveloped.be, DNS:undeveloped.co.uk, DNS:undeveloped.domains, DNS:dan.com, DNS:www.dan.com, DNS:undeveloped.fr, DNS:undeveloped.nu

takeout.js version: 1.3.1
nodejs version: v20.3.0

**Comment by s0urfruit** [comment]
I genuinely have no idea how this issue even occurs, or where “api.takeout.io” even comes from.

Takeout is being shutdown on July 1st, in favor of another platform. 

Cheers,
Sourfruit

**Comment by siddiquiaffan** [comment]
Thanks for the response!

Can you tell me which platform the takeout is being discontinued in favor of?

**Comment by s0urfruit** [comment]
Absolutely! 

While it’s not ‘polished’ yet, it is moving to [Contiguity](https://contiguity.co)- a more fully featured communications service that uses what I learned from Takeout.

Currently, you’d only be able to sign up for the free tier and use some basic features— the SDKs aren’t done, the CLI is nearly done, Stripe is still in development mode, custom emails aren’t supported yet, etc. 

By June 30th, things will be done and released (ProductHunt, etc)
